#define LUAT_USE_GPIO 1
#define LUAT_USE_UART 1
#define LUAT_USE_I2C  1
#define LUAT_USE_SPI  1
#define LUAT_USE_ADC  1
#define LUAT_USE_PWM  1
#define LUAT_USE_WDT  1
#define LUAT_USE_PM  1
#define LUAT_USE_RTC 1
#define LUAT_USE_WLAN 1
#define LUAT_USE_SMS 1
#define LUAT_USE_MCU  1


#define LUAT_USE_CRYPTO  1
#define LUAT_USE_CJSON  1
#define LUAT_USE_ZBUFF  1
#define LUAT_USE_PACK  1
#define LUAT_USE_MINIZ 1

#define LUAT_USE_HMETA 1
#define LUAT_USE_FSKV 1


#define LUAT_USE_MQTT 1
#define LUAT_USE_FTP 1
#define LUAT_USE_WEBSOCKET 1

#define LUAT_USE_IOTAUTH 1
#define LUAT_USE_BIT64 1
#define LUAT_USE_ICONV 1

#define LUAT_HEAP_SIZE (200*1024)

#define LUAT_SCRIPT_SIZE 256
#define LUAT_SCRIPT_OTA_SIZE 192