#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Sat Feb 15 10:12:15 2025

#define DB_VERSION_UNIQ_ID "0x640770c7"

#endif //_DB_VERSION_H
