#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.80.213, Mon Apr  8 15:06:18 2024

#define DB_VERSION_UNIQ_ID "0x6bb12d2c"

#endif //_DB_VERSION_H
