#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Mon Mar 10 16:49:48 2025

#define DB_VERSION_UNIQ_ID "0x57763a51"

#endif //_DB_VERSION_H
