#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Fri Dec 27 18:19:18 2024

#define DB_VERSION_UNIQ_ID "0x23e57257"

#endif //_DB_VERSION_H
