#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Tue Feb 25 12:00:31 2025

#define DB_VERSION_UNIQ_ID "0x17474121"

#endif //_DB_VERSION_H
