#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.80.213, Thu Apr 18 14:10:26 2024

#define DB_VERSION_UNIQ_ID "0x152c5380"

#endif //_DB_VERSION_H
