#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Thu Aug 29 11:36:54 2024

#define DB_VERSION_UNIQ_ID "0x0af02534"

#endif //_DB_VERSION_H
