#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Mon Mar 31 11:51:32 2025

#define DB_VERSION_UNIQ_ID "0x489f2cfe"

#endif //_DB_VERSION_H
