#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Fri Jan 24 09:44:29 2025

#define DB_VERSION_UNIQ_ID "0x4c3c1284"

#endif //_DB_VERSION_H
