#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Wed Jan 15 14:30:24 2025

#define DB_VERSION_UNIQ_ID "0x2ff60cf1"

#endif //_DB_VERSION_H
