#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Fri Dec 13 15:51:03 2024

#define DB_VERSION_UNIQ_ID "0x4b0d2d19"

#endif //_DB_VERSION_H
