#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Mon Dec  9 13:13:30 2024

#define DB_VERSION_UNIQ_ID "0x590b428f"

#endif //_DB_VERSION_H
