#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Mon Mar 10 16:50:57 2025

#define DB_VERSION_UNIQ_ID "0x493b41f8"

#endif //_DB_VERSION_H
