#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Fri Jul 26 10:48:51 2024

#define DB_VERSION_UNIQ_ID "0x3ce30012"

#endif //_DB_VERSION_H
