#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.81.216, Sat Mar 29 09:52:22 2025

#define DB_VERSION_UNIQ_ID "0x32266f4a"

#endif //_DB_VERSION_H
